AWSTemplateFormatVersion: '2010-09-09'
Parameters:

  ProjectName:
    Type: String
    Default: Metabase
    Description: Nome do projeto

  VpcId:
    Type: AWS::EC2::VPC::Id
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  Environment:
    Type: String
    Default: prod
Resources:
  
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group do ECS Metabase. Recebe trafego somente do ALB na porta 3000 e acessa apenas servicos necessarios.
      VpcId: !Ref VpcId

      # ENTRADA somente ALB para ECS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: Permite trafego do ALB para o Metabase exclusivamente na porta 3000

      # SAIDA liberada (controle de acesso ao RDS é feito no SG do RDS)
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Saída liberada para qualquer destino

      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: Dominitax
        - Key: Application
          Value: metabase
        - Key: Component
          Value: sgs-ecs


Outputs:

  ECSSecurityGroupId:
    Description: Security Group do ECS Metabase
    Value: !Ref ECSSecurityGroup
    Export:
      Name: Metabase-EcsSecurityGroup

  ECSSecurityGroupArn:
    Description: ARN do Security Group do ECS
    Value: !GetAtt ECSSecurityGroup.GroupId