Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  Environment:
    Type: String
    Default: prod
Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group do RDS PostgreSQL. Aceita conexoes apenas do ECS.
      VpcId: !Ref VpcId

      # ENTRADA quem pode falar com o banco
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref ECSSecurityGroup
          Description: Permite conexao Postgres somente vinda do ECS Metabase

      # SAIDA respostas do banco
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Permite que o RDS responda as conexoes iniciadas
        
Outputs:
  RDSSecurityGroupId:
    Value: !Ref RDSSecurityGroup