Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  Environment:
    Type: String
    Default: prod
    
Resources:
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group do ECS Metabase. Recebe trafego somente do ALB na porta 3000 e acessa apenas servicos necessarios.
      VpcId: !Ref VpcId

      # ENTRADA somente ALB para ECS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: Permite trafego do ALB para o Metabase exclusivamente na porta 3000

      # SAIDA somente o necessario
      SecurityGroupEgress:
        # HTTPS — AWS APIs (Secrets Manager, CloudWatch, etc)
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS para AWS APIs

      Tags:
        - Key: Project
          Value: Metabase
        - Key: Component
          Value: ECS
        - Key: Environment
          Value: prod


Outputs:

  ECSSecurityGroupId:
    Description: Security Group do ECS Metabase
    Value: !Ref ECSSecurityGroup
    Export:
      Name: Metabase-EcsSecurityGroup

  ECSSecurityGroupArn:
    Description: ARN do Security Group do ECS
    Value: !GetAtt ECSSecurityGroup.GroupId