AWSTemplateFormatVersion: "2010-09-09"
Description: ALB público para Metabase (ECS)

Parameters:
  ProjectName:
    Type: String
    Default: Metabase
    Description: Nome do projeto

  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - hml
    Description: Ambiente da stack

  VpcId:
    Type: AWS::EC2::VPC::Id

  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>

  ALBSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ID do Security Group a ser associado ao ALB

Resources:

  ## 🌐 Load Balancer
  MetabaseALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: metabase-loadbalancer
      Scheme: internet-facing
      Type: application
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: Dominitax
        - Key: Application
          Value: metabase
        - Key: Component
          Value: alb

  ## 🎯 Target Group (ECS)
  MetabaseTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: metabase-target-group
      VpcId: !Ref VpcId
      Port: 3000
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /api/health
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5

  ## 🔁 Listener HTTP
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MetabaseALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MetabaseTargetGroup

Outputs:
  ALBDNS:
    Description: DNS público do ALB
    Value: !GetAtt MetabaseALB.DNSName

  TargetGroupArn:
    Description: Target Group para usar no ECS Service
    Value: !Ref MetabaseTargetGroup

  ALBSecurityGroupId:
    Value: !Ref ALBSecurityGroupId
