AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository for application

Parameters:
  ProjectName:
    Type: String
    Default: Metabase
    Description: Nome do projeto

  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - hml
    Description: Ambiente da stack
  
  RepositoryName:
    Type: String
    Default: my-app-repo
    Description: Nome do repositório ECR

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: Dominitax
        - Key: Application
          Value: metabase
        - Key: Component
          Value: ecr

Outputs:
  RepositoryUri:
    Description: URI do repositório ECR
    Value: !GetAtt ECRRepository.RepositoryUri

  RepositoryName:
    Description: Nome do repositório ECR
    Value: !Ref RepositoryName
