AWSTemplateFormatVersion: "2010-09-09"
Description: RDS PostgreSQL + Secret Manager para Metabase

Parameters:
  DBUser:
    Type: String
    Description: Nome do usuário do banco

  DBPassword:
    Type: String
    NoEcho: true
    Description: Senha do banco

  DBName:
    Type: String
    Default: metabase
    Description: Nome do banco

  DBInstanceClass:
    Type: String
    Default: db.t3.micro

  VpcId:
    Type: AWS::EC2::VPC::Id

  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

Resources:

  ## 🔐 Security Group do RDS
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acesso Postgres apenas do ECS
      VpcId: !Ref VpcId

  RDSSGIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RDSSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref ECSSecurityGroup

  ## 📦 Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets privadas
      SubnetIds: !Ref PrivateSubnets

  ## 🗄️ RDS
  MetabaseDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: metabase-db
      Engine: postgres
      EngineVersion: "15.14"
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20

      DBName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword

      VPCSecurityGroups:
        - !Ref RDSSecurityGroup

      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      MultiAZ: false
      DeletionProtection: false

  ## 🔐 Secret Manager (fonte da verdade)
  MetabaseDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: metabase/db
      Description: Credenciais do banco Metabase
      SecretString: !Sub |
        {
          "username": "${DBUser}",
          "password": "${DBPassword}",
          "host": "${MetabaseDB.Endpoint.Address}",
          "port": 5432,
          "dbname": "${DBName}"
        }

Outputs:
  DatabaseSecretArn:
    Description: ARN do Secret do banco
    Value: !Ref MetabaseDBSecret
    Export:
      Name: Metabase-DbSecretArn
