AWSTemplateFormatVersion: "2010-09-09"
Description: RDS PostgreSQL + Secret Manager para Metabase

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - hml
    Description: Ambiente da stack
  ProjectName:
    Type: String
    Default: Metabase
    Description: Nome do projeto
    
  DBUser:
    Type: String
    Description: Nome do usuário do banco

  DBPassword:
    Type: String
    NoEcho: true
    Description: Senha do banco

  DBName:
    Type: String
    Default: metabase
    Description: Nome do banco

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
  
  RDSSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ID do Security Group já existente para o RDS

  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Lista de subnets privadas para o DBSubnetGroup

Resources:
  ## 📦 Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets privadas para o RDS
      SubnetIds: !Ref PrivateSubnets
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  MetabaseDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: metabase-database
      Engine: postgres
      EngineVersion: "15.14"
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      DBName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref RDSSecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 3
      MultiAZ: true
      DeletionProtection: false
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: Dominitax
        - Key: Application
          Value: metabase
        - Key: Component
          Value: rds-secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  ## 🔐 Secret Manager (fonte da verdade)
  MetabaseDBUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: metabase/db-username
      SecretString: !Ref DBUser
      Description: Secret contendo o nome do usuario do banco de dados do Metabase
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: Dominitax
        - Key: Application
          Value: metabase
        - Key: Component
          Value: rds-secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
      
  MetabaseDBPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: metabase/db-password
      SecretString: !Ref DBPassword
      Description: Secret contendo a senha do banco de dados do Metabase
      Tags:
      - Key: Project
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment
      - Key: Owner
        Value: Dominitax
      - Key: Application
        Value: metabase
      - Key: Component
        Value: rds-secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain


Outputs:
  DatabaseUserSecretArn:
    Description: ARN do Secret do usuário do banco
    Value: !Ref MetabaseDBUserSecret
    Export:
      Name: Metabase-DbUserSecretArn

  DatabasePasswordSecretArn:
    Description: ARN do Secret da senha do banco
    Value: !Ref MetabaseDBPasswordSecret
    Export:
      Name: Metabase-DbPasswordSecretArn